all:
  hosts:
    node1:
      ansible_host: 89.169.174.203
      ip: 10.129.0.12
      access_ip: 10.129.0.12
    node2:
      ansible_host: 51.250.104.43
      ip: 10.129.0.29
      access_ip: 10.129.0.29
    node3:
      ansible_host: 84.201.165.130
      ip: 10.129.0.27
      access_ip: 10.129.0.27
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
