all:
  hosts:
    node1:
      ansible_host: 51.250.5.195
      ip: 10.128.0.17
      access_ip: 51.250.5.195
    node2:
      ansible_host: 51.250.64.32
      ip: 10.128.0.12
      access_ip: 51.250.64.32
    node3:
      ansible_host: 89.169.159.252
      ip: 10.128.0.38
      access_ip: 89.169.159.252
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
