all:
  hosts:
    node1:
      ansible_host: 130.193.42.213
      ip: 10.129.0.33
      access_ip: 10.129.0.33
    node2:
      ansible_host: 158.160.29.79
      ip: 10.129.0.38
      access_ip: 10.129.0.38
    node3:
      ansible_host: 130.193.41.139
      ip: 10.129.0.26
      access_ip: 10.129.0.26
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
