all:
  hosts:
    node1:
      ansible_host: 158.160.16.71
      ip: 10.129.0.11
      access_ip: 10.129.0.11
    node2:
      ansible_host: 51.250.111.72
      ip: 10.129.0.38
      access_ip: 10.129.0.38
    node3:
      ansible_host: 158.160.27.120
      ip: 10.129.0.3
      access_ip: 10.129.0.3
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
