all:
  hosts:
    node1:
      ansible_host: 89.169.166.162
      ip: 10.129.0.24
      access_ip: 10.129.0.24
    node2:
      ansible_host: 62.84.123.163
      ip: 10.129.0.11
      access_ip: 10.129.0.11
    node3:
      ansible_host: 51.250.24.63
      ip: 10.129.0.22
      access_ip: 10.129.0.22
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
